# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataPackageVersionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[DataPackageItemInfo]',
        'version_id': 'str'
    }

    attribute_map = {
        'items': 'items',
        'version_id': 'version_id'
    }

    def __init__(self, items=None, version_id=None):  # noqa: E501
        """DataPackageVersionInfo - a model defined in Swagger"""  # noqa: E501
        self._items = None
        self._version_id = None
        self.discriminator = None
        if items is not None:
            self.items = items
        if version_id is not None:
            self.version_id = version_id

    @property
    def items(self):
        """Gets the items of this DataPackageVersionInfo.  # noqa: E501


        :return: The items of this DataPackageVersionInfo.  # noqa: E501
        :rtype: list[DataPackageItemInfo]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this DataPackageVersionInfo.


        :param items: The items of this DataPackageVersionInfo.  # noqa: E501
        :type: list[DataPackageItemInfo]
        """

        self._items = items

    @property
    def version_id(self):
        """Gets the version_id of this DataPackageVersionInfo.  # noqa: E501


        :return: The version_id of this DataPackageVersionInfo.  # noqa: E501
        :rtype: str
        """
        return self._version_id

    @version_id.setter
    def version_id(self, version_id):
        """Sets the version_id of this DataPackageVersionInfo.


        :param version_id: The version_id of this DataPackageVersionInfo.  # noqa: E501
        :type: str
        """

        self._version_id = version_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataPackageVersionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataPackageVersionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
