# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MilestoneInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'actual_date': 'int',
        'description': 'str',
        'name': 'str',
        'planned_date': 'int',
        'uuid': 'str'
    }

    attribute_map = {
        'actual_date': 'actual_date',
        'description': 'description',
        'name': 'name',
        'planned_date': 'planned_date',
        'uuid': 'uuid'
    }

    def __init__(self, actual_date=None, description=None, name=None, planned_date=None, uuid=None):  # noqa: E501
        """MilestoneInfo - a model defined in Swagger"""  # noqa: E501
        self._actual_date = None
        self._description = None
        self._name = None
        self._planned_date = None
        self._uuid = None
        self.discriminator = None
        if actual_date is not None:
            self.actual_date = actual_date
        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if planned_date is not None:
            self.planned_date = planned_date
        if uuid is not None:
            self.uuid = uuid

    @property
    def actual_date(self):
        """Gets the actual_date of this MilestoneInfo.  # noqa: E501


        :return: The actual_date of this MilestoneInfo.  # noqa: E501
        :rtype: int
        """
        return self._actual_date

    @actual_date.setter
    def actual_date(self, actual_date):
        """Sets the actual_date of this MilestoneInfo.


        :param actual_date: The actual_date of this MilestoneInfo.  # noqa: E501
        :type: int
        """

        self._actual_date = actual_date

    @property
    def description(self):
        """Gets the description of this MilestoneInfo.  # noqa: E501


        :return: The description of this MilestoneInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MilestoneInfo.


        :param description: The description of this MilestoneInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this MilestoneInfo.  # noqa: E501


        :return: The name of this MilestoneInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MilestoneInfo.


        :param name: The name of this MilestoneInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def planned_date(self):
        """Gets the planned_date of this MilestoneInfo.  # noqa: E501


        :return: The planned_date of this MilestoneInfo.  # noqa: E501
        :rtype: int
        """
        return self._planned_date

    @planned_date.setter
    def planned_date(self, planned_date):
        """Sets the planned_date of this MilestoneInfo.


        :param planned_date: The planned_date of this MilestoneInfo.  # noqa: E501
        :type: int
        """

        self._planned_date = planned_date

    @property
    def uuid(self):
        """Gets the uuid of this MilestoneInfo.  # noqa: E501


        :return: The uuid of this MilestoneInfo.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this MilestoneInfo.


        :param uuid: The uuid of this MilestoneInfo.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MilestoneInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MilestoneInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
