# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScheduledEventParticipantInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attending': 'str',
        'participant': 'UserInfo'
    }

    attribute_map = {
        'attending': 'attending',
        'participant': 'participant'
    }

    def __init__(self, attending=None, participant=None):  # noqa: E501
        """ScheduledEventParticipantInfo - a model defined in Swagger"""  # noqa: E501
        self._attending = None
        self._participant = None
        self.discriminator = None
        if attending is not None:
            self.attending = attending
        if participant is not None:
            self.participant = participant

    @property
    def attending(self):
        """Gets the attending of this ScheduledEventParticipantInfo.  # noqa: E501


        :return: The attending of this ScheduledEventParticipantInfo.  # noqa: E501
        :rtype: str
        """
        return self._attending

    @attending.setter
    def attending(self, attending):
        """Sets the attending of this ScheduledEventParticipantInfo.


        :param attending: The attending of this ScheduledEventParticipantInfo.  # noqa: E501
        :type: str
        """

        self._attending = attending

    @property
    def participant(self):
        """Gets the participant of this ScheduledEventParticipantInfo.  # noqa: E501


        :return: The participant of this ScheduledEventParticipantInfo.  # noqa: E501
        :rtype: UserInfo
        """
        return self._participant

    @participant.setter
    def participant(self, participant):
        """Sets the participant of this ScheduledEventParticipantInfo.


        :param participant: The participant of this ScheduledEventParticipantInfo.  # noqa: E501
        :type: UserInfo
        """

        self._participant = participant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduledEventParticipantInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduledEventParticipantInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
